### ISSUE TITLE
Replace Picker with some sort of modal

### ISSUE THREAD

**Issue by moficodes** [cogrammer/Translator#14]
right now the code is using picker.

it works ok but there are some issues with it.

1. its different looking in ios and android. 

2. in ios it takes way too much space. 

we might be better off doing some sort of modal that pops up and we can make choice on it.

Something to think about.

**Comment by moficodes** [comment]
a second thought would be to use two different buttons for from and to languages. 
kind of similar to what google translate does.

![Screen Shot 2019-04-18 at 8 36 00 PM](https://user-images.githubusercontent.com/14829780/56399001-a3018100-6219-11e9-92e7-148078a760e2.png)

**Comment by Mdnkhan** [comment]
In the patch 21 the modals were implemented and UI followed same pattern as the Google translator

**Comment by Mdnkhan** [comment]
Replaced pickers with one modal containing all the language options
