### ISSUE TITLE
Multi level translation

### ISSUE THREAD

**Issue by moficodes** [cogrammer/Translator#5]
update the function so that it can handle translations that require more than one step.

for example 
finnish - french needs to go 
finnish-english-french

**Comment by ottoporami** [comment]
For unsupported models, translation api call(s) is to be done twice. 
/*
unsupported model id: source -> target
first call: lang_from: source, lang_to: en
second call: lang_from: en, lang_to: target
*/

**Comment by Mdnkhan** [comment]
Patch#22 added the ability to do cross language translation by implementing the model: 
from_lang - en - to_lang
